#!/usr/bin/env pwsh
# korvarix-llm - Open WebUI frontend-only install (Windows / WSL2 or Docker Desktop).
# Mirrors install.sh for the dev box: same .env, same volume, loopback only.
# Usage: ./install.ps1 [-Status|-Logs [n]|-Stop|-Start|-Restart|-Uninstall]

param(
    [switch]$Status,
    [int]$Logs = 0,
    [switch]$Stop,
    [switch]$Start,
    [switch]$Restart,
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"
Set-Location -LiteralPath $PSScriptRoot

$ContainerName = if ($env:CONTAINER_NAME) { $env:CONTAINER_NAME } else { "korvarix-llm" }
$VolumeName    = if ($env:VOLUME_NAME)    { $env:VOLUME_NAME }    else { "korvarix-llm-data" }

function Write-Log($m)  { Write-Host "==> $m" -ForegroundColor Cyan }
function Write-Warn2($m){ Write-Host "warn: $m" -ForegroundColor Yellow }
function Die($m)        { Write-Host "error: $m" -ForegroundColor Red; exit 1 }

function New-Secret {
    $b = [byte[]]::new(32); [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
    ([Convert]::ToBase64String($b) -replace "[+/=]", "").Substring(0, 64)
}

function Require-Docker {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        Die "docker not found - install Docker Desktop (with WSL2 backend): https://docs.docker.com/desktop/install/windows-install/"
    }
    docker info *> $null
    if ($LASTEXITCODE -ne 0) { Die "docker is installed but not reachable - start Docker Desktop first" }
}

function Read-DotEnv {
    $vars = @{}
    if (Test-Path .env) {
        foreach ($line in Get-Content .env) {
            if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$') {
                $vars[$Matches[1]] = $Matches[2].Trim('"')
            }
        }
    }
    $vars
}

function Ensure-Env {
    if (Test-Path .env) {
        $v = Read-DotEnv
        if (-not $v["WEBUI_SECRET_KEY"]) {
            Write-Warn2 "WEBUI_SECRET_KEY empty in .env - generating and appending"
            Add-Content .env ("WEBUI_SECRET_KEY=" + (New-Secret))
        }
        return
    }
    Write-Log "creating .env (edit it later, then re-run this script to apply)"
    @"
# korvarix-llm (Open WebUI frontend) - generated by install.ps1
# Edit, then re-run ./install.ps1 to apply. Never expose WEBUI_PORT publicly.

OPEN_WEBUI_IMAGE=ghcr.io/open-webui/open-webui:main
WEBUI_PORT=8210
WEBUI_SECRET_KEY=$(New-Secret)

# Bootstrap admin on FIRST boot only (leave empty to create in the UI)
WEBUI_ADMIN_EMAIL=
WEBUI_ADMIN_PASSWORD=
ENABLE_SIGNUP=False
ENABLE_LOGIN_FORM=True

# Models live on the separate LLM machine - set when it's up, e.g.
# OLLAMA_BASE_URL=http://10.0.0.5:11434
OLLAMA_BASE_URL=

OPENAI_API_BASE_URL=
OPENAI_API_KEY=

# ---- phase 2: korvarix.com SSO gate (uncomment when the gate is installed) --
# WEBUI_AUTH_TRUSTED_EMAIL_HEADER=X-Korvarix-Email
# WEBUI_AUTH_TRUSTED_NAME_HEADER=X-Korvarix-Name
# WEBUI_AUTH_SIGNOUT_REDIRECT_URL=https://korvarix.com/account
"@ | Set-Content -Encoding utf8 .env
    Write-Log "wrote .env"
}

function Up {
    Require-Docker
    Ensure-Env
    $vars = Read-DotEnv
    $image = if ($vars["OPEN_WEBUI_IMAGE"]) { $vars["OPEN_WEBUI_IMAGE"] } else { "ghcr.io/open-webui/open-webui:main" }
    $port  = if ($vars["WEBUI_PORT"])       { $vars["WEBUI_PORT"] }       else { "8210" }

    Write-Log "pulling $image"
    docker pull $image *> $null

    docker volume create $VolumeName *> $null

    $exists = docker ps -a --format '{{.Names}}' | Select-String -SimpleMatch $ContainerName
    if ($exists) {
        Write-Log "recreating container $ContainerName"
        docker rm -f $ContainerName *> $null
    } else {
        Write-Log "creating container $ContainerName"
    }

    # 127.0.0.1 binding: only the local proxy/gate can reach it
    docker run -d --name $ContainerName --restart unless-stopped `
        -p "127.0.0.1:${port}:8080" `
        --env-file .env `
        -v "${VolumeName}:/app/backend/data" `
        $image *> $null
    if ($LASTEXITCODE -ne 0) { Die "docker run failed - check ./install.ps1 -Logs 50" }

    Write-Log "korvarix-llm is up"
    Write-Host ("  local: http://127.0.0.1:{0}" -f $port)
}

if ($Logs -gt 0) { docker logs --tail $Logs -f $ContainerName; exit }
if ($Logs -lt 0){ docker logs -f $ContainerName; exit }
if ($Status) { docker ps --filter "name=^$ContainerName$" --format 'running: {{.Names}} ({{.Status}})'; exit }
if ($Stop)   { docker stop $ContainerName; exit }
if ($Start)  { docker start $ContainerName; exit }
if ($Restart){ docker restart $ContainerName; exit }
if ($Uninstall) { docker rm -f $ContainerName *> $null; Write-Log "container removed; volume '$VolumeName' kept"; exit }
Up