#!/usr/bin/env bash
# korvarix-llm - Open WebUI frontend-only install script.
#
# Installs Open WebUI as the LLM panel FRONTEND on this machine:
#   - no bundled models/Ollama (":main" image, not ":ollama")
#   - auth enabled, signup disabled, one local admin (headless bootstrap)
#   - binds to 127.0.0.1 ONLY - the reverse proxy (and later the korvarix
#     account gate) is the only way in; never expose WEBUI_PORT publicly
#   - models come later from the separate LLM machine via OLLAMA_BASE_URL
#
# Phase 2 (korvarix.com account + custom package gate) sits between the
# proxy and Open WebUI: it validates the korvarix session, checks the
# "LLM access" package entitlement, and injects the trusted headers
# (WEBUI_AUTH_TRUSTED_EMAIL_HEADER / _NAME_HEADER) that Open WebUI uses
# for SSO. This script already passes those knobs through when set.
#
# Usage:
#   ./install.sh              install or update (pull + recreate + checks)
#   ./install.sh check        strict verification: config loaded + upstream live
#   ./install.sh nginx        reverse proxy: LLM_DOMAIN -> 127.0.0.1:$WEBUI_PORT (Let's Encrypt)
#   ./install.sh nginx-remove remove the proxy site config
#   ./install.sh status       container health + proxy state
#   ./install.sh logs [n]     tail container logs
#   ./install.sh stop|start|restart
#   ./install.sh uninstall    remove container (keeps the data volume)
#
# Config: korvarix-llm/.env (created from the embedded template on first run;
# existing .env is never overwritten - edit it and re-run ./install.sh).

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

CONTAINER_NAME="${CONTAINER_NAME:-korvarix-llm}"
VOLUME_NAME="${VOLUME_NAME:-korvarix-llm-data}"

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarn:\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

require_docker() {
  if command -v docker >/dev/null 2>&1; then
    docker info >/dev/null 2>&1 || die "docker is installed but not reachable (daemon down or permissions - try: sudo usermod -aG docker \$USER, then re-login)"
    return 0
  fi
  warn "docker not found"
  printf 'Install Docker on this machine now? [y/N] '
  read -r reply
  case "$reply" in
    y|Y)
      log "installing docker (get.docker.com)"
      curl -fsSL https://get.docker.com | sh
      command -v docker >/dev/null 2>&1 || die "docker install did not produce a docker binary - install it manually and re-run"
      ;;
    *) die "docker is required: https://docs.docker.com/engine/install/" ;;
  esac
}

ensure_env() {
  if [[ -f .env ]]; then
    # shellcheck disable=SC1091
    set -a; source .env; set +a
    if [[ -z "${WEBUI_SECRET_KEY:-}" ]]; then
      warn "WEBUI_SECRET_KEY empty in .env - generating one and appending"
      printf 'WEBUI_SECRET_KEY=%s\n' "$(generate_secret)" >> .env
      set -a; source .env; set +a
    fi
    return 0
  fi
  log "creating .env (edit it later and re-run $0 to apply)"
  cat > .env <<EOF
# korvarix-llm (Open WebUI frontend) - generated by install.sh
# Edit, then re-run ./install.sh to apply. Never expose WEBUI_PORT publicly.

# Open WebUI image tag ("main" = stable; ":cuda" adds GPU for local inference,
# irrelevant for this frontend-only box).
OPEN_WEBUI_IMAGE=${OPEN_WEBUI_IMAGE:-ghcr.io/open-webui/open-webui:main}

# Loopback port the reverse proxy (and later the korvarix gate) points at.
WEBUI_PORT=${WEBUI_PORT:-8210}

# Hard requirement when auth is enabled - generated on first install.
WEBUI_SECRET_KEY=$(generate_secret)

# Bootstrap admin for Open WebUI's OWN login (first boot only; the gate does
# NOT use this password - it uses the OPEN_WEBUI_API_KEY below for avatars)
WEBUI_ADMIN_EMAIL=${WEBUI_ADMIN_EMAIL:-}
WEBUI_ADMIN_PASSWORD=
ENABLE_SIGNUP=False
ENABLE_LOGIN_FORM=True

# Models live on the separate LLM machine - fill this in when it's up,
# e.g. OLLAMA_BASE_URL=http://10.0.0.5:11434 (or an https endpoint).
# Until then the panel runs with no models (frontend-only, as intended).
OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-}

# Optional: any OpenAI-compatible endpoint as an alternative/extra backend.
OPENAI_API_BASE_URL=
OPENAI_API_KEY=

# ---- nginx proxy (./install.sh nginx) ---------------------------------------
# Public hostname that proxies to 127.0.0.1:WEBUI_PORT (see above). DNS must
# point at this machine and port 80 must be reachable for Let's Encrypt.
LLM_DOMAIN=${LLM_DOMAIN:-}
# Email for Let's Encrypt expiry notices.
LE_EMAIL=${LE_EMAIL:-admin@korvarix.com}

# ---- phase 2: korvarix.com SSO gate (uncomment when the gate is installed) --
# The gate validates the korvarix session + "LLM access" package, then injects
# these headers. Do NOT set them while WEBUI_PORT is reachable by anyone
# except the gate/proxy - trusted headers are only safe behind that hop.
# WEBUI_AUTH_TRUSTED_EMAIL_HEADER=X-Korvarix-Email
# WEBUI_AUTH_TRUSTED_NAME_HEADER=X-Korvarix-Name
# WEBUI_AUTH_SIGNOUT_REDIRECT_URL=https://korvarix.com/account
EOF
  log "wrote .env - set WEBUI_ADMIN_EMAIL (+PASSWORD, OWUI bootstrap), OPEN_WEBUI_API_KEY and OLLAMA_BASE_URL when ready"
}

up() {
  require_docker
  ensure_env
  local image="${OPEN_WEBUI_IMAGE:-ghcr.io/open-webui/open-webui:main}"
  local port="${WEBUI_PORT:-8210}"

  log "pulling $image"
  docker pull "$image" >/dev/null

  docker volume create "$VOLUME_NAME" >/dev/null

  if docker ps -a --format '{{.Names}}' | grep -qx "$CONTAINER_NAME"; then
    log "recreating container $CONTAINER_NAME"
    docker rm -f "$CONTAINER_NAME" >/dev/null
  else
    log "creating container $CONTAINER_NAME"
  fi

  # --add-host lets the container reach an Ollama box on the LAN via
  # host.docker.internal once OLLAMA_BASE_URL is set. When the gate network
  # exists (gate installed), join it so the gate can resolve "open-webui".
  local net_args=()
  if docker network inspect korvarix-llm-net >/dev/null 2>&1; then
    net_args=(--network korvarix-llm-net --network-alias open-webui)
  fi

  # ---- korvarix branding (theme + logos) -------------------------------------
  # Open WebUI serves /static/custom.css and /static/{logo,favicon,splash}.png
  # from its static dir; per-file -v mounts override exactly those paths with
  # the korvarix set (theme/custom.css + scripts/make-branding.mjs output).
  # WEBUI_NAME renames the UI text; ENABLE_VERSION_UPDATE_CHECK stays on the
  # stock value. Assets are (re)generated fresh on every install so an updated
  # logo.svg lands on the next re-run, like the gate's --no-cache rule.
  local theme_args=()
  if [[ -f "$HERE/theme/custom.css" ]]; then
    log "branding: korvarix theme + logos"
    mkdir -p "$HERE/theme/assets"
    # regenerate the PNG/ICO set from the korvarix vector logo (needs node;
    # if node is missing on this box, fall back to the committed copies)
    if command -v node >/dev/null 2>&1; then
      node "$HERE/scripts/make-branding.mjs" "$HERE/theme/korvarix-logo.svg" "$HERE/theme/assets" >/dev/null 2>&1 \
        || warn "branding: generator failed - using committed theme assets"
    else
      warn "branding: node not found - using committed theme assets"
    fi
    theme_args+=(
      -v "$HERE/theme/custom.css:/app/backend/open_webui/static/custom.css:ro"
      -v "$HERE/theme/assets/logo.png:/app/backend/open_webui/static/logo.png:ro"
      # index.html declares favicon.png AND favicon.svg; browsers prefer the
      # SVG - missing this mount left the stock Open WebUI tab icon
      -v "$HERE/theme/assets/favicon.svg:/app/backend/open_webui/static/favicon.svg:ro"
      -v "$HERE/theme/assets/favicon.png:/app/backend/open_webui/static/favicon.png:ro"
      -v "$HERE/theme/assets/favicon-96x96.png:/app/backend/open_webui/static/favicon-96x96.png:ro"
      -v "$HERE/theme/assets/favicon.ico:/app/backend/open_webui/static/favicon.ico:ro"
      -v "$HERE/theme/assets/apple-touch-icon.png:/app/backend/open_webui/static/apple-touch-icon.png:ro"
      -v "$HERE/theme/assets/splash.png:/app/backend/open_webui/static/splash.png:ro"
      -v "$HERE/theme/assets/splash-dark.png:/app/backend/open_webui/static/splash-dark.png:ro"
      -v "$HERE/theme/assets/web-app-manifest-192x192.png:/app/backend/open_webui/static/web-app-manifest-192x192.png:ro"
      -v "$HERE/theme/assets/web-app-manifest-512x512.png:/app/backend/open_webui/static/web-app-manifest-512x512.png:ro"
    )
    # brand name in the UI (title, docs header). QUOTED value: .env is sourced
    # by install.sh and by the container's --env-file, and an unquoted space
    # ("WEBUI_NAME=Korvarix AI") makes bash try to run `AI` as a command.
    if ! grep -q '^WEBUI_NAME=' .env 2>/dev/null; then
      printf 'WEBUI_NAME="Korvarix AI"\n' >> .env
    fi
  else
    warn "branding: theme/custom.css not found - skipping (upload the whole folder)"
  fi

  docker run -d \
    --name "$CONTAINER_NAME" \
    --restart unless-stopped \
    --add-host=host.docker.internal:host-gateway \
    "${net_args[@]}" \
    "${theme_args[@]}" \
    -p "127.0.0.1:${port}:8080" \
    --env-file .env \
    -v "${VOLUME_NAME}:/app/backend/data" \
    "$image" >/dev/null

  # trusted headers ON: Open WebUI signs users in from the gate's headers.
  # (WEBUI_AUTH_TRUSTED_EMAIL_HEADER / _NAME_HEADER are read from .env when
  # uncommented there; without the gate these are absent -> normal login form)
  log "korvarix-llm is up"
  printf '  local:     http://127.0.0.1:%s\n' "$port"
  printf '  data:      docker volume %s\n' "$VOLUME_NAME"
  printf '  next:      ./install.sh gate   (korvarix SSO + avatars), then\n'
  printf '             ./install.sh nginx (llm.korvarix.com -> gate).\n'
}

# ---- korvarix SSO gate: node sidecar between nginx and Open WebUI ------------
# Validates the korvarix SSO code, checks the LLM access package, syncs the
# korvarix avatar (no gravatar), and proxies with the trusted headers.
# shellcheck disable=SC2034  # kept for parity with the documented folder layout
GATE_DIR="$HERE/gate"
GATE_PORT_DEFAULT=8211

gate_env() {
  # append the gate knobs to .env once. NOTE: an EMPTY LLM_SSO_KEY= (e.g. from
  # a `cp .env.example .env`) counts as "not configured" - the gate refuses to
  # start without a real key, so generate one whenever the value is blank.
  if ! grep -q '^LLM_SSO_KEY=.\+' .env 2>/dev/null; then
    # drop any empty placeholder line first so we don't end up with two
    sed -i '/^LLM_SSO_KEY=$/d' .env 2>/dev/null || true
    printf '\n# ---- korvarix SSO gate (gate/gate.js) ---------------------------------------\n' >> .env
    printf '# shared secret with korvarix-base (set the SAME value there: LLM_SSO_KEY)\n' >> .env
    printf 'LLM_SSO_KEY=%s\n' "$(generate_secret)" >> .env
    printf '# the gate runs here; nginx points at this port (not WEBUI_PORT)\n' >> .env
    printf 'GATE_PORT=%s\n' "$GATE_PORT_DEFAULT" >> .env
    printf '# OWUI API key so the gate can sync korvarix avatars (create in OWUI as\n' >> .env
    printf '# admin: Settings -> Account -> API Keys; paste the sk-... token here)\n' >> .env
    printf 'OPEN_WEBUI_API_KEY=\n' >> .env
    printf '# open webui 302-forwards profile images to their origin URL (korvarix CDN)\n' >> .env
    printf 'ENABLE_PROFILE_IMAGE_URL_FORWARDING=true\n' >> .env
    # trusted headers: the whole point of the gate - enable them now
    sed -i 's|^# WEBUI_AUTH_TRUSTED_EMAIL_HEADER=|WEBUI_AUTH_TRUSTED_EMAIL_HEADER=|' .env
    sed -i 's|^# WEBUI_AUTH_TRUSTED_NAME_HEADER=|WEBUI_AUTH_TRUSTED_NAME_HEADER=|' .env
    sed -i 's|^# WEBUI_AUTH_SIGNOUT_REDIRECT_URL=|WEBUI_AUTH_SIGNOUT_REDIRECT_URL=|' .env
    log "gate settings appended to .env - set LLM_SSO_KEY (same value in korvarix-base) + OPEN_WEBUI_API_KEY"
  fi
  # shellcheck disable=SC1091
  set -a; source .env; set +a
}

# nginx_setup calls this when it detects a gate config: ensure .env actually
# has the gate section (older installs created .env without it). An EMPTY
# LLM_SSO_KEY also counts as missing (the gate cannot run without one).
gate_ensure_env_keys() {
  if ! grep -q '^LLM_SSO_KEY=.\+' .env 2>/dev/null; then
    gate_env
  fi
  # always re-source so GATE_PORT etc. are current
  # shellcheck disable=SC1091
  set -a; source .env; set +a
}

gate_run() {
  require_docker
  # preflight: the gate needs its companion files next to this script. A bare
  # `install.sh` upload is not enough - the whole korvarix-llm folder must be
  # on the box (install alone works without them, gate does not).
  local missing=()
  [[ -f "$HERE/Dockerfile.gate" ]] || missing+=("Dockerfile.gate")
  [[ -f "$HERE/gate/gate.js" ]] || missing+=("gate/gate.js")
  [[ -f "$HERE/lib/@korvarix/shared/env.js" ]] || missing+=("lib/@korvarix/shared/env.js")
  if ((${#missing[@]})); then
    die "missing gate files in $HERE: ${missing[*]}
  - the 'install' command only needs install.sh, but the GATE does not
  - upload the WHOLE korvarix-llm folder (with Dockerfile.gate, gate/, lib/)
    to this directory, then re-run ./install.sh gate"
  fi
  gate_env
  local gport="${GATE_PORT:-$GATE_PORT_DEFAULT}"

  # the gate runs as a second container on the same docker network as
  # open-webui: it reaches OWUI by container alias (no host node needed).
  # If OWUI was created by an older install (default bridge network), connect
  # it to our network with the alias the gate resolves as WEBUI_HOST.
  docker network inspect korvarix-llm-net >/dev/null 2>&1 || docker network create korvarix-llm-net >/dev/null
  docker network connect --alias open-webui korvarix-llm-net "$CONTAINER_NAME" 2>/dev/null || true

  # sync WEBUI_HOST for the gate into .env (idempotent single line)
  if grep -q '^WEBUI_HOST=' .env 2>/dev/null; then
    sed -i 's|^WEBUI_HOST=.*|WEBUI_HOST=open-webui|' .env
  else
    printf 'WEBUI_HOST=open-webui\n' >> .env
  fi
  # the gate must dial the CONTAINER-INTERNAL port (8080), not the host-published
  # WEBUI_PORT (8210) - container-to-container traffic bypasses the -p mapping
  if grep -q '^WEBUI_INTERNAL_PORT=' .env 2>/dev/null; then
    sed -i 's|^WEBUI_INTERNAL_PORT=.*|WEBUI_INTERNAL_PORT=8080|' .env
  else
    printf 'WEBUI_INTERNAL_PORT=8080\n' >> .env
  fi
  # re-source after .env edits
  # shellcheck disable=SC1091
  set -a; source .env; set +a

  # build a tiny runtime image (node:22-alpine + the gate sources, zero deps).
  # --no-cache: the image is ~50MB of base + a few kB of sources - always
  # rebuild fresh so an updated gate.js can NEVER be shadowed by layer cache
  # (the exact failure mode when fixes "don't take").
  docker build --no-cache -q -f "$HERE/Dockerfile.gate" -t korvarix-llm-gate "$HERE" >/dev/null || \
    docker build --no-cache -f "$HERE/Dockerfile.gate" -t korvarix-llm-gate "$HERE" || die "gate image build failed - see output above"

  if docker ps -a --format '{{.Names}}' | grep -qx "korvarix-llm-gate"; then
    log "recreating container korvarix-llm-gate"
    docker rm -f korvarix-llm-gate >/dev/null
  fi
  docker run -d \
    --name korvarix-llm-gate \
    --restart unless-stopped \
    --network korvarix-llm-net \
    -p "127.0.0.1:${gport}:8211" \
    --env-file .env \
    -e GATE_BIND=0.0.0.0 \
    -e GATE_TRACE=1 \
    -e WEBUI_HOST=open-webui \
    -e WEBUI_INTERNAL_PORT=8080 \
    -v /etc/korvarix-llm:/etc/korvarix-llm:ro \
    -v /var/log/korvarix:/var/log/korvarix \
    -e KORVARIX_POLICY_PATH=/etc/korvarix-llm/korvarix-policy.json \
    -e KORVARIX_USAGE_LOG=/var/log/korvarix/llm-usage.jsonl \
    korvarix-llm-gate >/dev/null
  # policy + usage: /etc/korvarix-llm (station-pushed policy, ro) and
  # /var/log/korvarix (usage JSONL, rw) ride in from the host when they exist;
  # without them the gate runs on built-in defaults and skips usage logging.

  # prove the running container carries the CURRENT gate.js: compare the hash
  # inside the container with the file on disk
  local want
  want="$(sha256sum "$HERE/gate/gate.js" | cut -d' ' -f1)"
  local have
  have="$(docker exec korvarix-llm-gate sha256sum /gate/gate/gate.js 2>/dev/null | cut -d' ' -f1 || true)"
  if [[ "$have" != "$want" ]]; then
    die "gate image does NOT contain the current gate.js (image=$have file=$want) - build cache or upload issue"
  fi
  log "gate verified: container gate.js matches the repo copy (sha256 ${want:0:12}…)"

  log "gate running as container korvarix-llm-gate (host 127.0.0.1:$gport -> open-webui container)"
  # if nginx was set up BEFORE the gate existed, it still targets Open WebUI
  # directly (bypassing SSO) - re-render it onto the gate now
  if command -v nginx >/dev/null 2>&1 && [[ -f /etc/nginx/conf.d/korvarix-llm.conf || -f /etc/nginx/sites-available/korvarix-llm.conf || -f /etc/nginx/http.d/korvarix-llm.conf ]]; then
    log "existing nginx vhost found - repointing it at the gate"
    nginx_setup
  else
    printf '  next: ./install.sh nginx (llm.korvarix.com -> gate)\n'
  fi
}

# ---- nginx reverse proxy: llm.korvarix.com -> 127.0.0.1:$WEBUI_PORT ---------
# Installs/updates the site config, fetches a Let's Encrypt cert via certbot
# (same pattern as the game-node node-setup.sh), validates AND verifies the
# config is actually loaded (nginx -T), then probes the upstream.
# Config layout is DETECTED (conf.d vs sites-available, webroot variants) so
# it works on Debian/Ubuntu, RHEL-family, Alpine (http.d), Arch and SUSE.
NGINX_CONF=""
NGINX_WEBROOT=""
NGINX_CONF_LINK=""

detect_nginx_layout() {
  local nginx_conf_dir
  NGINX_CONF_LINK=""
  nginx_conf_dir="$(nginx -V 2>&1 | grep -o 'conf-path=[^ ]*' | cut -d= -f2 | xargs dirname)"
  nginx_conf_dir="${nginx_conf_dir:-/etc/nginx}"
  # 1) Debian/Ubuntu: conf.d exists but is NOT included; sites-* is.
  #    RHEL/Arch/SUSE: conf.d IS included. Alpine calls it http.d.
  if [[ -d "$nginx_conf_dir/sites-enabled" ]] && ! grep -qsE 'include\s+.*conf\.d/\*\.conf' "$nginx_conf_dir/nginx.conf"; then
    NGINX_CONF="$nginx_conf_dir/sites-available/korvarix-llm.conf"
    NGINX_CONF_LINK="$nginx_conf_dir/sites-enabled/korvarix-llm.conf"
  elif [[ -d "$nginx_conf_dir/conf.d" ]] && grep -qsE 'include\s+.*conf\.d/\*\.conf' "$nginx_conf_dir/nginx.conf"; then
    NGINX_CONF="$nginx_conf_dir/conf.d/korvarix-llm.conf"
  elif [[ -d "$nginx_conf_dir/http.d" ]]; then
    NGINX_CONF="$nginx_conf_dir/http.d/korvarix-llm.conf"
  else
    # last resort: drop it next to nginx.conf with a legal name
    NGINX_CONF="$nginx_conf_dir/korvarix-llm.conf"
  fi
  # ACME webroot: prefer the distro default docroot that actually exists
  for candidate in /var/www/html /var/www /srv/www /usr/share/nginx/html; do
    if [[ -d "$candidate" ]]; then
      NGINX_WEBROOT="$candidate"
      break
    fi
  done
  NGINX_WEBROOT="${NGINX_WEBROOT:-/var/www/html}"
  mkdir -p "$NGINX_WEBROOT"
}

nginx_upstream_block() {
  local port="$1"        # WEBUI_PORT (kept for the check/summary output)
  local with_tls="$2"    # "tls" = full vhost with 443; anything else = HTTP-only (pre-cert)
  local proxy_target="$3" # gate port when the gate is installed, else WEBUI_PORT
  local http_block=""
  local tls_block=""
  # ::1 listen breaks nginx -t/start on hosts without IPv6 (common on VPS)
  local listen6="    listen [::]:80;"
  if ! ip -6 addr show >/dev/null 2>&1 || ! ip -6 addr show | grep -qs "inet6.*scope global\|inet6.*scope link"; then
    listen6=""
  fi
  if [[ "$with_tls" == "tls" ]]; then
    local listen6_tls=""
    if [[ -n "$listen6" ]]; then listen6_tls="    listen [::]:443 ssl;"; fi
    http_block="location / {
        return 301 https://\$host\$request_uri;
    }"
    tls_block="server {
    # http2 as its own directive (nginx >= 1.25; the old 'listen ... http2'
    # form is deprecated and warns on nginx 1.28+)
    listen 443 ssl;
    http2 on;
${listen6_tls}
    server_name ${LLM_DOMAIN};

    ssl_certificate     ${NGINX_CERT};
    ssl_certificate_key ${NGINX_KEY};

    # Static assets + websockets bypass the node gate entirely: Open WebUI
    # serves both without auth, and the node relay's connection shape was
    # losing response headers under nginx load (body served, headers gone).
    # The gate keeps what needs gating: the SPA root, login, and gated APIs.
    location /_app/ {
        proxy_pass http://127.0.0.1:${port};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
    location /static/ {
        proxy_pass http://127.0.0.1:${port};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
    location /assets/ {
        proxy_pass http://127.0.0.1:${port};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
    location /manifest.json {
        proxy_pass http://127.0.0.1:${port};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
    location /ws/ {
        proxy_pass http://127.0.0.1:${port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade    \$http_upgrade;
        proxy_set_header Connection \$korvarix_llm_connection;
        proxy_set_header Host       \$host;
        proxy_read_timeout  86400s;
        proxy_send_timeout  86400s;
        proxy_buffering     off;
    }

    # Open WebUI streams tokens over websockets (socket.io) - same shape as
    # the game-node proxy blocks (Upgrade/Connection + long read timeouts)
    location / {
        proxy_pass http://127.0.0.1:${proxy_target};

        proxy_http_version 1.1;

        proxy_set_header Upgrade    \$http_upgrade;
        proxy_set_header Connection \$korvarix_llm_connection;

        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # LLM responses can stream for minutes; SSE + websockets need this
        proxy_read_timeout  86400s;
        proxy_send_timeout  86400s;
        proxy_buffering     off;
    }

    # phase 2: the korvarix SSO gate drops in front of this location block,
    # injecting the trusted headers; Open WebUI stays loopback-only.
}"
  else
    # pre-cert bootstrap: serve plain HTTP so the ACME challenge can land
    http_block="location / {
        proxy_pass http://127.0.0.1:${proxy_target};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }"
  fi
  cat <<EOF
# korvarix-llm (Open WebUI frontend) - managed by korvarix-llm/install.sh
map \$http_upgrade \$korvarix_llm_connection {
    default upgrade;
    ''      close;
}

server {
    listen 80;
${listen6}
    server_name ${LLM_DOMAIN};

    # ACME HTTP-01 challenge (certbot webroot)
    location /.well-known/acme-challenge/ { root ${NGINX_WEBROOT}; }

    ${http_block}
}

${tls_block}
EOF
}

nginx_cmd() {
  # requires root; the container part runs unprivileged
  [[ $(id -u) -eq 0 ]] || die "nginx setup needs root (re-run with sudo)"
  # distro-agnostic package install: apt / dnf / yum / zypper / pacman / apk.
  # (the target box may not use the Debian package layout at all)
  local pkg
  if command -v nginx >/dev/null 2>&1 && command -v certbot >/dev/null 2>&1; then
    return 0
  fi
  if command -v apt-get >/dev/null 2>&1; then
    # certbot with the nginx plugin so the renewal hook config stays in sync
    pkg="nginx certbot python3-certbot-nginx"
    log "installing via apt: $pkg"
    apt-get update -qq
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq $pkg || die "apt-get install failed - install nginx + certbot manually and re-run"
  elif command -v dnf >/dev/null 2>&1; then
    pkg="nginx certbot python3-certbot-nginx"
    log "installing via dnf: $pkg"
    dnf install -y -q $pkg || die "dnf install failed - (EPEL needed on RHEL clones: dnf install -y epel-release) then re-run"
  elif command -v yum >/dev/null 2>&1; then
    pkg="nginx certbot python3-certbot-nginx"
    log "installing via yum: $pkg"
    yum install -y -q epel-release 2>/dev/null || true
    yum install -y -q $pkg || die "yum install failed - install nginx + certbot manually and re-run"
  elif command -v zypper >/dev/null 2>&1; then
    pkg="nginx certbot"
    log "installing via zypper: $pkg"
    zypper --non-interactive install $pkg || die "zypper install failed - install nginx + certbot manually and re-run"
  elif command -v pacman >/dev/null 2>&1; then
    pkg="nginx certbot"
    log "installing via pacman: $pkg"
    pacman -Sy --noconfirm --needed $pkg || die "pacman install failed - install nginx + certbot manually and re-run"
  elif command -v apk >/dev/null 2>&1; then
    pkg="nginx certbot"
    log "installing via apk: $pkg"
    apk add --no-cache $pkg || die "apk install failed - install nginx + certbot manually and re-run"
  else
    die "no supported package manager found (apt/dnf/yum/zypper/pacman/apk) - install nginx + certbot manually and re-run"
  fi
  command -v nginx >/dev/null 2>&1 || die "nginx still not found after install - install it manually and re-run"
  command -v certbot >/dev/null 2>&1 || warn "certbot not found after install - obtain the certificate manually or install certbot"
}

# start/reload nginx across init systems without tripping `set -e`
nginx_service() {
  local action="$1"
  if command -v systemctl >/dev/null 2>&1 && systemctl is-system-running >/dev/null 2>&1; then
    case "$action" in
      start)  systemctl enable --now nginx >/dev/null 2>&1 || true ;;
      reload) systemctl reload nginx >/dev/null 2>&1 || true ;;
    esac
  else
    case "$action" in
      start)  (service nginx start >/dev/null 2>&1 || nginx >/dev/null 2>&1 || true) ;;
      reload) (service nginx reload >/dev/null 2>&1 || nginx -s reload >/dev/null 2>&1 || true) ;;
    esac
  fi
}

# verify our vhost is REALLY loaded by the running nginx (nginx -T dumps the
# full effective config); checks for our marker + the domain
nginx_verify_loaded() {
  local domain="$1"
  local dump
  dump="$(nginx -T 2>/dev/null)" || return 1
  grep -q "korvarix-llm (Open WebUI frontend)" <<<"$dump" || return 1
  grep -q "server_name ${domain}" <<<"$dump"
}

# can we reach the Open WebUI upstream on loopback?
# retries for up to ~60s: first boot initializes the DB and takes a while
nginx_probe_upstream() {
  local port="$1"
  local attempt
  for attempt in 1 2 3 4 5 6; do
    if command -v curl >/dev/null 2>&1; then
      curl -fs -o /dev/null --max-time 5 "http://127.0.0.1:${port}/" 2>/dev/null && return 0
    elif command -v wget >/dev/null 2>&1; then
      wget -q -O /dev/null -T 5 "http://127.0.0.1:${port}/" 2>/dev/null && return 0
    else
      # no curl/wget: just check something is listening
      if (exec 3<>"/dev/tcp/127.0.0.1/${port}") 2>/dev/null; then
        exec 3>&- 3<&- 2>/dev/null || true
        return 0
      fi
    fi
    ((attempt < 6)) && sleep 10
  done
  return 1
}

nginx_setup() {
  ensure_env
  local port="${WEBUI_PORT:-8210}"
  # when the gate is installed, nginx proxies to the GATE (it owns SSO +
  # avatars and forwards to Open WebUI itself); otherwise straight to OWUI
  local proxy_target="$port"
  if grep -q '^LLM_SSO_KEY=.\+' .env 2>/dev/null; then
    proxy_target="${GATE_PORT:-$GATE_PORT_DEFAULT}"
    gate_ensure_env_keys
    log "gate detected - nginx will proxy llm.korvarix.com -> 127.0.0.1:${proxy_target} (gate -> Open WebUI)"
  else
    log "no gate configured - nginx will proxy straight to Open WebUI (run './install.sh gate' for SSO)"
  fi
  if [[ -z "${LLM_DOMAIN:-}" ]]; then
    LLM_DOMAIN="$(grep -E '^LLM_DOMAIN=' .env 2>/dev/null | cut -d= -f2 || true)"
  fi
  [[ -n "$LLM_DOMAIN" ]] || die "set LLM_DOMAIN=llm.korvarix.com in korvarix-llm/.env first"
  NGINX_CERT="/etc/letsencrypt/live/${LLM_DOMAIN}/fullchain.pem"
  NGINX_KEY="/etc/letsencrypt/live/${LLM_DOMAIN}/privkey.pem"
  nginx_cmd
  detect_nginx_layout

  log "writing $NGINX_CONF (${LLM_DOMAIN} -> 127.0.0.1:${port})"
  # first pass: HTTP-only vhost (no cert yet - nginx -t would fail on missing
  # ssl_certificate files); the ACME challenge lands here
  mkdir -p "$(dirname "$NGINX_CONF")"
  nginx_upstream_block "$port" "http" "$proxy_target" > "$NGINX_CONF"
  # Debian sites-* layout needs the enabled symlink; conf.d needs none
  if [[ -n "$NGINX_CONF_LINK" ]]; then
    mkdir -p "$(dirname "$NGINX_CONF_LINK")"
    ln -sf "$NGINX_CONF" "$NGINX_CONF_LINK"
  fi

  # start nginx with the HTTP-only vhost so the ACME challenge can land
  nginx -t || die "nginx config test failed - inspect $NGINX_CONF"
  nginx_service start
  nginx_service reload

  local le_dir="/etc/letsencrypt/live/${LLM_DOMAIN}"
  if [[ ! -d "$le_dir" ]]; then
    log "obtaining Let's Encrypt certificate for ${LLM_DOMAIN} (HTTP-01; DNS must point here, port 80 open)"
    certbot certonly --webroot -w "$NGINX_WEBROOT" -d "$LLM_DOMAIN" \
      --non-interactive --agree-tos -m "${LE_EMAIL:-admin@korvarix.com}" --keep-until-expiring \
      || die "certbot failed - check DNS for ${LLM_DOMAIN} and that port 80 is reachable"
  else
    log "certificate for ${LLM_DOMAIN} already present (renewals run via certbot timer)"
  fi

  # render the final config now that the cert exists, reload, verify
  nginx_upstream_block "$port" "tls" "$proxy_target" > "$NGINX_CONF"
  nginx -t || die "nginx config test failed after cert install"
  nginx_service reload

  # SELinux (RHEL-family): allow nginx to connect to the loopback upstream
  if command -v getenforce >/dev/null 2>&1 && [[ "$(getenforce 2>/dev/null)" == "Enforcing" ]]; then
    if command -v setsebool >/dev/null 2>&1; then
      setsebool -P httpd_can_network_connect 1 2>/dev/null || \
        warn "setsebool httpd_can_network_connect failed - proxy may 502 (run manually as root)"
    fi
  fi

  # auto-reload nginx on renewal (same pattern as tlscertgen node-setup.sh)
  local hook="/etc/letsencrypt/renewal-hooks/deploy/korvarix-llm-reload"
  mkdir -p "$(dirname "$hook")"
  printf '#!/bin/sh\nsystemctl reload nginx 2>/dev/null || service nginx reload 2>/dev/null || nginx -s reload\n' > "$hook"
  chmod +x "$hook"

  # VERIFY: config actually loaded + upstream answering
  if nginx_check; then
    # summary reflects what nginx ACTUALLY targets: the gate when installed,
    # Open WebUI directly otherwise
    local summary_target="${proxy_target}"
    local summary_label="Open WebUI"
    if [[ "$summary_target" != "$port" ]]; then summary_label="gate (korvarix SSO) -> Open WebUI"; fi
    log "nginx is serving https://${LLM_DOMAIN} -> http://127.0.0.1:${summary_target} (${summary_label})"
    printf '  config:    %s\n' "$NGINX_CONF"
    printf '  renew:     certbot renew (systemd timer) + deploy hook %s\n' "$hook"
  else
    die "nginx setup finished with warnings above - fix them and re-run ./install.sh nginx"
  fi
}

# end-to-end MIME probe through the FULL public chain: request a module script
# the way a browser does (HTTPS + Host + Origin) and assert the content-type
# arrives intact. This is the check that catches the "" MIME class of bugs -
# a per-hop probe (owui -> gate -> nginx) can all pass while the public
# response is still broken.
nginx_mime_check() {
  ensure_env
  local domain="${LLM_DOMAIN:-}"
  if [[ -z "$domain" && -f .env ]]; then
    domain="$(grep -E '^LLM_DOMAIN=' .env 2>/dev/null | cut -d= -f2 || true)"
  fi
  [[ -n "$domain" ]] || { warn "mime-check: no LLM_DOMAIN set"; return 1; }
  command -v curl >/dev/null 2>&1 || { warn "mime-check needs curl"; return 1; }
  # any real asset path works; the SPA entry script is deterministic
  local url="https://${domain}/"
  local headers
  headers="$(curl -s -D - -o /dev/null --max-time 10 "$url" -H "Host: ${domain}" -A "korvarix-llm-check" 2>/dev/null)"
  if grep -qi "^HTTP.* 200" <<<"$headers" && grep -qi "^content-type: *text/html" <<<"$headers"; then
    log "mime-check: public document OK (200 text/html)"
  else
    warn "mime-check: public document unexpected - headers:"
    printf '%s\n' "$headers" | head -12
    return 1
  fi
}

# post-install verification used by `nginx`, and by `install`/`update` and `check`
nginx_check() {
  local port="${WEBUI_PORT:-8210}"
  local domain="${LLM_DOMAIN:-}"
  if [[ -z "$domain" && -f .env ]]; then
    domain="$(grep -E '^LLM_DOMAIN=' .env 2>/dev/null | cut -d= -f2 || true)"
  fi
  local problems=()

  # 1. binaries present?
  command -v nginx >/dev/null 2>&1 || problems+=("nginx not installed (run: ./install.sh nginx as root)")

  # 2. config file written, valid, and actually LOADED?
  if [[ -n "$NGINX_CONF" && -f "$NGINX_CONF" ]]; then
    if command -v nginx >/dev/null 2>&1; then
      nginx -t >/dev/null 2>&1 || problems+=("nginx config test FAILED - run: nginx -t")
      if [[ -n "$domain" ]] && ! nginx_verify_loaded "$domain"; then
        problems+=("config exists but is NOT loaded by nginx - include path wrong? (debug: nginx -T | grep korvarix)")
      fi
    fi
  else
    problems+=("vhost config not written${NGINX_CONF:+ (expected at $NGINX_CONF)}")
  fi

  # 3. cert present when TLS is configured?
  if [[ -n "$domain" && -f "$NGINX_CONF" ]] && grep -q "ssl_certificate" "$NGINX_CONF" 2>/dev/null && [[ ! -d "/etc/letsencrypt/live/${domain}" ]]; then
    problems+=("vhost references a TLS cert but /etc/letsencrypt/live/${domain} is missing (run: ./install.sh nginx as root)")
  fi

  # 4. upstream reachable? when the gate is installed, nginx forwards to the
  # gate (which forwards to Open WebUI) - probe what nginx actually targets
  local upstream_port="$port"
  local upstream_label="Open WebUI"
  if grep -q '^LLM_SSO_KEY=.\+' .env 2>/dev/null; then
    upstream_port="${GATE_PORT:-$GATE_PORT_DEFAULT}"
    upstream_label="gate (korvarix SSO)"
  fi
  if ! nginx_probe_upstream "$upstream_port"; then
    problems+=("$upstream_label not reachable on 127.0.0.1:${upstream_port} (run: ./install.sh / ./install.sh gate)")
  fi

  if ((${#problems[@]})); then
    for p in "${problems[@]}"; do warn "$p"; done
    return 1
  fi
  log "check: nginx vhost loaded + upstream 127.0.0.1:${upstream_port} (${upstream_label}) responding"
  return 0
}

nginx_remove() {
  [[ $(id -u) -eq 0 ]] || die "needs root"
  detect_nginx_layout
  if [[ -f "$NGINX_CONF" ]]; then
    rm -f "$NGINX_CONF" "$NGINX_CONF_LINK"
    nginx -t >/dev/null 2>&1 && nginx_service reload
    log "removed $NGINX_CONF"
  else
    warn "no $NGINX_CONF"
  fi
}

# status helper: find the config wherever this box's nginx puts it.
# exit 0 + sets NGINX_CONF only when the vhost actually exists.
local_proxy_status() {
  local found=""
  for c in /etc/nginx/conf.d/korvarix-llm.conf /etc/nginx/sites-available/korvarix-llm.conf /etc/nginx/http.d/korvarix-llm.conf /etc/nginx/korvarix-llm.conf; do
    [[ -f "$c" ]] && { found="$c"; break; }
  done
  if [[ -n "$found" ]]; then
    NGINX_CONF="$found"
    grep -m1 server_name "$found" | sed 's/^ *//;s/;/ /' | sed "s/^/proxy:    (${found}) /"
    return 0
  fi
  NGINX_CONF=""
  return 1
}

case "${1:-install}" in
  install|update)
    up
    # built-in check: only when the proxy is already configured (fresh boxes
    # stay quiet). Verifies the vhost still lines up with the new container.
    if local_proxy_status >/dev/null 2>&1; then
      if ! nginx_check; then
        warn "re-run './install.sh nginx' after fixing the warnings above"
      fi
    fi
    ;;
  check)
    # strict verification: nginx loaded + upstream answering + public MIME
    ensure_env
    local_proxy_status >/dev/null 2>&1 || true
    nginx_check
    nginx_mime_check || true
    ;;
  gate)
    gate_run
    ;;
  nginx)
    nginx_setup
    ;;
  nginx-remove)
    nginx_remove
    ;;
  status)
    docker ps --filter "name=^${CONTAINER_NAME}$" --format 'running: {{.Names}} ({{.Status}})'
    docker inspect --format 'image: {{.Config.Image}}' "$CONTAINER_NAME" 2>/dev/null || warn "not installed"
    local_proxy_status || warn "proxy: not configured (run: ./install.sh nginx)"
    true
    ;;
  logs) docker logs ${2:+--tail "$2"} -f "$CONTAINER_NAME" ;;
  stop)    docker stop "$CONTAINER_NAME" ;;
  start)   docker start "$CONTAINER_NAME" ;;
  restart) docker restart "$CONTAINER_NAME" ;;
  uninstall)
    docker rm -f "$CONTAINER_NAME" 2>/dev/null || true
    log "container removed; data volume '$VOLUME_NAME' kept (docker volume rm $VOLUME_NAME to drop it)"
    ;;
  *) die "unknown command: $1 (use install|update|check|gate|nginx|nginx-remove|status|logs|stop|start|restart|uninstall)" ;;
esac